name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the version of Node.js specified in your project

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Adjust the build command as necessary

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ANGULAR_AUTH_SECRET }}
          publish_dir: cic/dist/browser  # Adjust the directory to your build output
